import re, glob

# Light-theme class -> dark value. Dark surfaces (stone-800/900, hero, footer) are left alone.
BG = {
  'white': '#1c1917', 'stone-50': '#1f1c1a', 'stone-100': '#292524', 'stone-200': '#35302d',
  'stone-300': '#44403c', '[#FBFBF9]': '#0f0d0c', '[#fbfbf9]': '#0f0d0c',
  'emerald-50': 'rgba(16,185,129,.12)', 'emerald-100': 'rgba(16,185,129,.2)',
  'amber-50': 'rgba(245,158,11,.12)', 'amber-100': 'rgba(245,158,11,.2)',
  'rose-50': 'rgba(244,63,94,.12)', 'rose-100': 'rgba(244,63,94,.2)',
  'red-50': 'rgba(239,68,68,.12)', 'red-100': 'rgba(239,68,68,.2)',
  'sky-50': 'rgba(14,165,233,.12)', 'sky-100': 'rgba(14,165,233,.2)',
  'blue-50': 'rgba(59,130,246,.12)', 'blue-100': 'rgba(59,130,246,.2)',
  'purple-50': 'rgba(168,85,247,.12)', 'purple-100': 'rgba(168,85,247,.2)',
  'green-50': 'rgba(34,197,94,.12)', 'green-100': 'rgba(34,197,94,.2)',
  'teal-50': 'rgba(20,184,166,.12)', 'orange-50': 'rgba(249,115,22,.12)', 'yellow-50': 'rgba(234,179,8,.12)',
}
TEXT = {
  'stone-950': '#fafaf9', 'stone-900': '#fafaf9', 'stone-800': '#f5f5f4', 'stone-700': '#e7e5e4',
  'stone-600': '#d6d3d1', 'stone-500': '#a8a29e', 'stone-400': '#8f8883',
  '[#1E293B]': '#f5f5f4', '[#1e293b]': '#f5f5f4',
  'emerald-950': '#a7f3d0', 'emerald-900': '#6ee7b7', 'emerald-800': '#6ee7b7', 'emerald-700': '#34d399',
  'amber-950': '#fde68a', 'amber-900': '#fcd34d', 'amber-800': '#fcd34d', 'amber-700': '#fbbf24',
  'rose-900': '#fda4af', 'rose-800': '#fda4af', 'rose-700': '#fb7185', 'rose-600': '#fb7185',
  'red-800': '#fca5a5', 'red-700': '#f87171', 'red-600': '#f87171',
  'sky-900': '#7dd3fc', 'sky-800': '#7dd3fc', 'sky-700': '#38bdf8',
  'blue-900': '#93c5fd', 'blue-800': '#93c5fd', 'blue-700': '#60a5fa',
  'purple-950': '#d8b4fe', 'purple-900': '#d8b4fe', 'purple-800': '#d8b4fe', 'purple-700': '#c084fc',
  'green-800': '#86efac', 'green-700': '#4ade80',
}
BORDER = {
  'stone-50': '#292524', 'stone-100': '#292524', 'stone-200': '#35302d', 'stone-300': '#44403c',
  'emerald-100': 'rgba(52,211,153,.25)', 'emerald-200': 'rgba(52,211,153,.3)', 'emerald-300': 'rgba(52,211,153,.4)',
  'amber-100': 'rgba(251,191,36,.25)', 'amber-200': 'rgba(251,191,36,.3)', 'amber-300': 'rgba(251,191,36,.4)',
  'rose-100': 'rgba(251,113,133,.25)', 'rose-200': 'rgba(251,113,133,.3)', 'red-200': 'rgba(248,113,113,.3)',
  'sky-200': 'rgba(56,189,248,.3)', 'blue-200': 'rgba(96,165,250,.3)', 'purple-200': 'rgba(192,132,252,.3)',
}
GRAD = {k: v for k, v in BG.items() if k not in ('stone-200', 'stone-300')}
PROPS = {'bg': ('background-color', BG), 'text': ('color', TEXT), 'border': ('border-color', BORDER),
         'divide': (None, BORDER), 'from': ('--tw-gradient-from', GRAD), 'via': ('--tw-gradient-via', GRAD),
         'to': ('--tw-gradient-to', GRAD)}
VARIANTS = {'': '', 'hover:': ':hover', 'focus:': ':focus', 'active:': ':active', 'group-hover:': None}

def esc(c):
    return re.sub(r'([:/\[\]#.])', r'\\\1', c)

classes = set()
for f in glob.glob('src/**/*.tsx', recursive=True) + ['index.html']:
    classes |= set(re.findall(r'[\w:\-\[\]#/.]+', open(f).read()))

rules = []
for c in sorted(classes):
    m = re.fullmatch(r'((?:hover|focus|active|group-hover):)?(bg|text|border|divide|from|via|to)-([a-z]+-\d+|white|\[#[0-9A-Fa-f]{6}\])(?:/(\d+))?', c)
    if not m:
        continue
    variant, kind, color, alpha = m.group(1) or '', m.group(2), m.group(3), m.group(4)
    prop, table = PROPS[kind]
    if color not in table:
        continue
    # Translucent white is a glass effect on dark headers; leave it.
    if color == 'white' and alpha and int(alpha) < 50:
        continue
    value = table[color]
    if alpha and value.startswith('#'):
        value = f'color-mix(in srgb, {value} {alpha}%, transparent)'
    if variant == 'group-hover:':
        sel = f'html.dark .group:hover .{esc(c)}'
    else:
        sel = f'html.dark .{esc(c)}{VARIANTS[variant]}'
    if kind == 'divide':
        rules.append(f'{sel} > :not(:last-child) {{ border-color: {value}; }}')
    else:
        rules.append(f'{sel} {{ {prop}: {value}; }}')

header = """/* Generated by scripts/gen-dark-css.py: dark-mode overrides for the light colours used in components.
   Unlayered so they win over Tailwind's utility layer. Regenerate after adding new colours. */
html.dark { color-scheme: dark; }
html.dark body { background-color: #0f0d0c; color: #f5f5f4; }
html.dark input, html.dark textarea, html.dark select { color: #f5f5f4; }
html.dark input::placeholder, html.dark textarea::placeholder { color: #78716c; }
html.dark .leaflet-container { background: #1c1917; }
"""
footer = """
/* Dark text on bright amber/yellow badges and buttons must stay dark. */
html.dark :is(.text-stone-900, .text-stone-950, .text-stone-800):is([class*="bg-amber-2"], [class*="bg-amber-3"], [class*="bg-amber-4"], [class*="bg-amber-5"], [class*="bg-yellow-"]) { color: #1c1917; }
"""
open('src/dark.css', 'w').write(header + '\n'.join(rules) + '\n' + footer)
print(len(rules), 'rules')
